// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function AddConnection(arg1:config.ConnectionConfig):Promise<void>;

export function GetConnections():Promise<Array<config.ConnectionConfig>>;

export function Greet(arg1:string):Promise<string>;

export function RemoveConnection(arg1:string):Promise<void>;

export function TestConnection(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;
