// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function CancelTransfer(arg1) {
  return window['go']['main']['App']['CancelTransfer'](arg1);
}

export function ChangeDirectory(arg1, arg2) {
  return window['go']['main']['App']['ChangeDirectory'](arg1, arg2);
}

export function CloseSSH(arg1) {
  return window['go']['main']['App']['CloseSSH'](arg1);
}

export function ConnectLocalShell(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectLocalShell'](arg1, arg2, arg3, arg4);
}

export function ConnectSSH(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['ConnectSSH'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CreateDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateDirectory'](arg1, arg2);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteFiles(arg1, arg2) {
  return window['go']['main']['App']['DeleteFiles'](arg1, arg2);
}

export function DeletePassword(arg1) {
  return window['go']['main']['App']['DeletePassword'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function DownloadFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFiles'](arg1, arg2, arg3);
}

export function EscapeJSON(arg1) {
  return window['go']['main']['App']['EscapeJSON'](arg1);
}

export function FormatJSON(arg1) {
  return window['go']['main']['App']['FormatJSON'](arg1);
}

export function GetConnection(arg1) {
  return window['go']['main']['App']['GetConnection'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetCurrentPath(arg1) {
  return window['go']['main']['App']['GetCurrentPath'](arg1);
}

export function GetFileInfo(arg1, arg2) {
  return window['go']['main']['App']['GetFileInfo'](arg1, arg2);
}

export function GetMonitoringData(arg1) {
  return window['go']['main']['App']['GetMonitoringData'](arg1);
}

export function GetPassword(arg1) {
  return window['go']['main']['App']['GetPassword'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTransferStatus(arg1) {
  return window['go']['main']['App']['GetTransferStatus'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HasPassword(arg1) {
  return window['go']['main']['App']['HasPassword'](arg1);
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListSSHSessions() {
  return window['go']['main']['App']['ListSSHSessions']();
}

export function MinifyJSON(arg1) {
  return window['go']['main']['App']['MinifyJSON'](arg1);
}

export function RemoveConnection(arg1) {
  return window['go']['main']['App']['RemoveConnection'](arg1);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2, arg3);
}

export function ResizeLocalShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeLocalShell'](arg1, arg2, arg3);
}

export function ResizeSSH(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeSSH'](arg1, arg2, arg3);
}

export function SavePassword(arg1, arg2) {
  return window['go']['main']['App']['SavePassword'](arg1, arg2);
}

export function SelectDownloadDirectory() {
  return window['go']['main']['App']['SelectDownloadDirectory']();
}

export function SelectSSHKeyFile() {
  return window['go']['main']['App']['SelectSSHKeyFile']();
}

export function SelectUploadFiles() {
  return window['go']['main']['App']['SelectUploadFiles']();
}

export function SendLocalShellData(arg1, arg2) {
  return window['go']['main']['App']['SendLocalShellData'](arg1, arg2);
}

export function SendSSHData(arg1, arg2) {
  return window['go']['main']['App']['SendSSHData'](arg1, arg2);
}

export function ShowErrorDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowErrorDialog'](arg1, arg2);
}

export function ShowMessageDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowMessageDialog'](arg1, arg2);
}

export function ShowQuestionDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowQuestionDialog'](arg1, arg2);
}

export function TestConnection(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function UploadFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFiles'](arg1, arg2, arg3);
}

export function ValidateJSON(arg1) {
  return window['go']['main']['App']['ValidateJSON'](arg1);
}
